# Uncomment this line to define a global platform for your project
platform :ios, '7.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'DTKDropdownMenu' do
pod 'DTKDropdownMenu', '~> 0.0.3'
end

target 'DTKDropdownMenuTests' do

end

target 'DTKDropdownMenuUITests' do

end

