platform :ios, '8.0'
inhibit_all_warnings!
use_frameworks!
target 'Meizi' do

pod 'AFNetworking'
pod 'YYCache'
pod 'hpple'
pod 'MJRefresh'
pod 'MJExtension'
pod 'SDWebImage'
pod 'UIActivityIndicator-for-SDWebImage'
pod 'DACircularProgress'

end
