---
install:
  - git submodule update --init --recursive
test_script:
  - .\projects\VS12\Debug\test_bad_pointers.exe
  - .\projects\VS12\Debug\test_basic_lookup.exe
  - .\projects\VS12\Debug\test_data_entry_list.exe
  - .\projects\VS12\Debug\test_data_types.exe
  - .\projects\VS12\Debug\test_dump.exe
  - .\projects\VS12\Debug\test_get_value_pointer_bug.exe
  - .\projects\VS12\Debug\test_get_value.exe
  - .\projects\VS12\Debug\test_ipv4_start_cache.exe
  - .\projects\VS12\Debug\test_ipv6_lookup_in_ipv4.exe
  - .\projects\VS12\Debug\test_metadata.exe
  - .\projects\VS12\Debug\test_no_map_get_value.exe
  - .\projects\VS12\Debug\test_read_node.exe
  - .\projects\VS12\Debug\test_version.exe
notifications:
  - auth_token:
      secure: X+ymndzchVeC2LYsehzOt/GEMFfZJeTENeAU9lwNwTuCxBXFJNkuwZLd9joAtHgykHQoYqmEv/nH64+MA6nTlw==
    channel: ci
    on_build_failure: true
    on_build_status_changed: true
    on_build_success: true
    provider: Slack
  - on_build_failure: true
    on_build_status_changed: true
    on_build_success: false
    provider: Email
    subject: 'AppVeyor build {{status}}'
    to:
      - dev-ci@maxmind.com
