# Uncomment this line to define a global platform for your project
platform :ios, '7.0'
inhibit_all_warnings!

target 'YUKitSample' do
    pod 'AFNetworking' , '~>2.5.4'
    pod 'BlocksKit', '~> 2.2.5'
    pod 'SDWebImage', '~> 3.7.3'
    pod 'MJRefresh', '~> 2.2.0'
    pod	'Masonry','~> 0.6.2'
end

